clean:
	rm -f 8_PUZZLE/output_ASTAR.txt \
	      8_PUZZLE/output_BDS.txt \
	      8_PUZZLE/output_IDS.txt \
	      8_PUZZLE/puzzle_solution_astar.html \
	      8_PUZZLE/puzzle_solution_bds.html \
	      8_PUZZLE/puzzle_solution_ids.html
